server:
  port: 8081

#对象

#student:
#  name: qitong
#  age: 3

#行内写法
student: {name: 骐通 ,age: 3}

#数组
pets:
  - cat
  - dog
  - pig

#行内写法 pets: [cat,dog,pig]

person:
  name: qinjiang
  age: 3
  happy: false
  birthday: 2000/01/01
  map: {k1: v1,k2: v2}
  list:
    - code
    - girl
    - music
  dog:
    name: 旺财
    age: 1

